"""initial schema

Revision ID: 289573d39f13
Revises: 
Create Date: 2026-01-18 05:10:26.094272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289573d39f13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=15), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nom_complet', sa.String(length=255), nullable=False),
    sa.Column('niveau', sa.Integer(), nullable=False),
    sa.Column('filiere', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('competences', sa.Text(), nullable=True),
    sa.Column('centres_interet', sa.Text(), nullable=True),
    sa.Column('reseaux_sociaux', sa.Text(), nullable=True),
    sa.Column('photo_profil', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule'),
    sa.UniqueConstraint('token')
    )
    op.create_table('mentor_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('date_attribution', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surprises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('type_media', sa.String(length=20), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surprises')
    op.drop_table('mentor_assignments')
    op.drop_table('students')
    # ### end Alembic commands ###
