"""add system_states

Revision ID: 633da92a6a5a
Revises: 289573d39f13
Create Date: 2026-01-20 00:47:36.278166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633da92a6a5a'
down_revision = '289573d39f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentors_assigned', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_state')
    # ### end Alembic commands ###
