"""init schema

Revision ID: af7f042524c9
Revises: 
Create Date: 2026-01-17 12:17:29.895994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7f042524c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=15), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nom_complet', sa.String(length=255), nullable=False),
    sa.Column('niveau', sa.Integer(), nullable=False),
    sa.Column('filiere', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('competences', sa.Text(), nullable=True),
    sa.Column('centres_interet', sa.Text(), nullable=True),
    sa.Column('reseaux_sociaux', sa.Text(), nullable=True),
    sa.Column('photo_profil', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('mentor_assignments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'students', ['mentor_id'], ['id'])
        batch_op.create_foreign_key(None, 'students', ['mentee_id'], ['id'])

    with op.batch_alter_table('surprises', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'students', ['mentor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surprises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('mentor_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('students')
    # ### end Alembic commands ###
